name: kids_learn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts:
  signature: ^5.3.0
  flutter_colorpicker: ^1.0.3  # or latest
  scribble: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.7
  get: ^4.7.2
  provider: ^6.0.6

flutter_native_splash:
  color: "#f6f2ed"
  image: assets/images/ic_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    image: assets/images/ic_logo.png
    color: "#f6f2ed"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ic_splash1.png
    - assets/images/ic_logo.png
    - assets/images/Home/ic_home_bg.png
    - assets/images/Home/ic_category1.png
    - assets/images/Home/ic_category2.png
    - assets/images/Home/ic_category3.png
    - assets/images/Home/ic_category4.png
    - assets/images/Home/ic_category5.png
    - assets/images/Home/ic_category6.png
    - assets/images/Home/ic_learn.png
    - assets/images/Home/ic_draw.png
    - assets/images/Home/ic_tap.png
    - assets/images/Home/ic_sleep.png
    - assets/images/Home/ic_puzzle.png
    - assets/images/Home/ic_maths.png
    - assets/images/Home/ic_spelling.png
    - assets/images/Home/ic_quiz.png
    - assets/images/categoryList/ic_bg.png
    - assets/images/categoryList/ic_alpha.png
    - assets/images/categoryList/ic_animals.png
    - assets/images/categoryList/ic_birds.png
    - assets/images/categoryList/ic_bodypart.png
    - assets/images/categoryList/ic_categoryListBg.png
    - assets/images/categoryList/ic_color.png
    - assets/images/categoryList/ic_commingsoon.png
    - assets/images/categoryList/ic_numbers.png
    - assets/images/categoryList/ic_shape1.png
    - assets/images/categoryList/ic_shape2.png
    - assets/images/categoryList/ic_shape3.png
    - assets/images/categoryList/ic_shape4.png
    - assets/images/categoryList/ic_shape5.png
    - assets/images/categoryList/ic_shape6.png
    - assets/images/categoryList/ic_shape7.png
    - assets/images/categoryList/ic_shape8.png
    - assets/images/categoryList/ic_shapes.png
    - assets/images/categoryList/ic_vegetables.png
    - assets/images/categoryDetailList/alphabets/ic_apple.png
    - assets/images/categoryDetailList/alphabets/ic_ball.png
    - assets/images/categoryDetailList/alphabets/ic_cat.png
    - assets/images/categoryDetailList/alphabets/ic_dog.png
    - assets/images/categoryDetailList/alphabets/ic_elephent.png
    - assets/images/categoryDetailList/alphabets/ic_fish.png
    - assets/images/categoryDetailList/alphabets/ic_grapes.png
    - assets/images/categoryDetailList/alphabets/ic_horse.png
    - assets/images/categoryDetailList/alphabets/ic_icecream.png
    - assets/images/categoryDetailList/alphabets/ic_joker.png
    - assets/images/categoryDetailList/alphabets/ic_kite.png
    - assets/images/categoryDetailList/alphabets/ic_lion.png
    - assets/images/categoryDetailList/alphabets/ic_monkey.png
    - assets/images/categoryDetailList/alphabets/ic_nest.png
    - assets/images/categoryDetailList/alphabets/ic_orange.png
    - assets/images/categoryDetailList/alphabets/ic_owl.png
    - assets/images/categoryDetailList/alphabets/ic_parrot.png
    - assets/images/categoryDetailList/alphabets/ic_rabbit.png
    - assets/images/categoryDetailList/alphabets/ic_sparrow.png
    - assets/images/categoryDetailList/alphabets/ic_tiger.png
    - assets/images/categoryDetailList/alphabets/ic_umbrella.png
    - assets/images/categoryDetailList/alphabets/ic_violion.png
    - assets/images/categoryDetailList/alphabets/ic_watch.png
    - assets/images/categoryDetailList/alphabets/ic_xtree.png
    - assets/images/categoryDetailList/alphabets/ic_yak.png
    - assets/images/categoryDetailList/alphabets/ic_zebra.png
    - assets/images/categoryDetailList/ic_commonShape.png
    - assets/images/categoryDetailList/ic_categoryItembg.png
    - assets/images/categoryDetailList/ic_iteamBg.png
    - assets/images/categoryDetailList/numbers/ic_number1.png
    - assets/images/categoryDetailList/numbers/ic_number2.png
    - assets/images/categoryDetailList/numbers/ic_number3.png
    - assets/images/categoryDetailList/numbers/ic_number4.png
    - assets/images/categoryDetailList/numbers/ic_number5.png
    - assets/images/categoryDetailList/numbers/ic_number6.png
    - assets/images/categoryDetailList/numbers/ic_number7.png
    - assets/images/categoryDetailList/numbers/ic_number8.png
    - assets/images/categoryDetailList/numbers/ic_number9.png
    - assets/images/categoryDetailList/numbers/ic_number0.png
    - assets/images/categoryDetailList/colors/ic_color_white.png
    - assets/images/categoryDetailList/colors/ic_black.png
    - assets/images/categoryDetailList/colors/ic_blue.png
    - assets/images/categoryDetailList/colors/ic_brown.png
    - assets/images/categoryDetailList/colors/ic_cyan.png
    - assets/images/categoryDetailList/colors/ic_gray.png
    - assets/images/categoryDetailList/colors/ic_green.png
    - assets/images/categoryDetailList/colors/ic_light_green.png
    - assets/images/categoryDetailList/colors/ic_orange.png
    - assets/images/categoryDetailList/colors/ic_pink.png
    - assets/images/categoryDetailList/colors/ic_purple.png
    - assets/images/categoryDetailList/colors/ic_red.png
    - assets/images/categoryDetailList/colors/ic_sky_blue.png
    - assets/images/categoryDetailList/colors/ic_yellow.png
    - assets/images/categoryDetailList/shapes/ic_circle.png
    - assets/images/categoryDetailList/shapes/ic_corn.png
    - assets/images/categoryDetailList/shapes/ic_cube.png
    - assets/images/categoryDetailList/shapes/ic_cylinder.png
    - assets/images/categoryDetailList/shapes/ic_diamond.png
    - assets/images/categoryDetailList/shapes/ic_heart.png
    - assets/images/categoryDetailList/shapes/ic_hexagonal.png
    - assets/images/categoryDetailList/shapes/ic_octagon.png
    - assets/images/categoryDetailList/shapes/ic_oval.png
    - assets/images/categoryDetailList/shapes/ic_pentagon.png
    - assets/images/categoryDetailList/shapes/ic_prism.png
    - assets/images/categoryDetailList/shapes/ic_rectangle.png
    - assets/images/categoryDetailList/shapes/ic_star.png
    - assets/images/categoryDetailList/shapes/ic_traingle.png
    - assets/images/categoryDetailList/bodyparts/ic_arm.png
    - assets/images/categoryDetailList/bodyparts/ic_chest.png
    - assets/images/categoryDetailList/bodyparts/ic_ears.png
    - assets/images/categoryDetailList/bodyparts/ic_elbow.png
    - assets/images/categoryDetailList/bodyparts/ic_eye.png
    - assets/images/categoryDetailList/bodyparts/ic_eyebrows.png
    - assets/images/categoryDetailList/bodyparts/ic_face.png
    - assets/images/categoryDetailList/bodyparts/ic_fingers.png
    - assets/images/categoryDetailList/bodyparts/ic_hair.png
    - assets/images/categoryDetailList/bodyparts/ic_hand.png
    - assets/images/categoryDetailList/bodyparts/ic_heart.png
    - assets/images/categoryDetailList/bodyparts/ic_heel.png
    - assets/images/categoryDetailList/bodyparts/ic_kidney.png
    - assets/images/categoryDetailList/bodyparts/ic_knee.png
    - assets/images/categoryDetailList/bodyparts/ic_legs.png
    - assets/images/categoryDetailList/bodyparts/ic_lips.png
    - assets/images/categoryDetailList/bodyparts/ic_lungs.png
    - assets/images/categoryDetailList/bodyparts/ic_nails.png
    - assets/images/categoryDetailList/bodyparts/ic_neck.png
    - assets/images/categoryDetailList/bodyparts/ic_nose.png
    - assets/images/categoryDetailList/bodyparts/ic_sholuder.png
    - assets/images/categoryDetailList/bodyparts/ic_skeleton.png
    - assets/images/categoryDetailList/bodyparts/ic_skin.png
    - assets/images/categoryDetailList/bodyparts/ic_skull.png
    - assets/images/categoryDetailList/bodyparts/ic_sole.png
    - assets/images/categoryDetailList/bodyparts/ic_stomach.png
    - assets/images/categoryDetailList/bodyparts/ic_teeth.png
    - assets/images/categoryDetailList/bodyparts/ic_thumb.png
    - assets/images/categoryDetailList/bodyparts/ic_tongue.png
    - assets/images/categoryDetailList/bodyparts/ic_waist.png
    - assets/images/categoryDetailList/bodyparts/ic_wrist.png
    - assets/images/drawing/ic_draw_bg.png
    - assets/images/drawing/ic_alpha.png
    - assets/images/drawing/ic_colors.png
    - assets/images/drawing/ic_numbers.png
    - assets/images/drawing/ic_shapes.png
    - assets/images/categoryDetailList/animals/ic_bear.png
    - assets/images/categoryDetailList/animals/ic_buffalo.png
    - assets/images/categoryDetailList/animals/ic_camel.png
    - assets/images/categoryDetailList/animals/ic_cat.png
    - assets/images/categoryDetailList/animals/ic_chimpanze.png
    - assets/images/categoryDetailList/animals/ic_cow.png
    - assets/images/categoryDetailList/animals/ic_dear.png
    - assets/images/categoryDetailList/animals/ic_dog.png
    - assets/images/categoryDetailList/animals/ic_donkey.png
    - assets/images/categoryDetailList/animals/ic_elephant.png
    - assets/images/categoryDetailList/animals/ic_fox.png
    - assets/images/categoryDetailList/animals/ic_giraffe.png
    - assets/images/categoryDetailList/animals/ic_goat.png
    - assets/images/categoryDetailList/animals/ic_gorila.png
    - assets/images/categoryDetailList/animals/ic_horse.png
    - assets/images/categoryDetailList/animals/ic_hyena.png
    - assets/images/categoryDetailList/animals/ic_kangaroo.png
    - assets/images/categoryDetailList/animals/ic_lion.png
    - assets/images/categoryDetailList/animals/ic_lropard.png
    - assets/images/categoryDetailList/animals/ic_monkey.png
    - assets/images/categoryDetailList/animals/ic_pig.png
    - assets/images/categoryDetailList/animals/ic_puma.png
    - assets/images/categoryDetailList/animals/ic_rabbit.png
    - assets/images/categoryDetailList/animals/ic_rat.png
    - assets/images/categoryDetailList/animals/ic_reindeer.png
    - assets/images/categoryDetailList/animals/ic_rhino.png
    - assets/images/categoryDetailList/animals/ic_sheep.png
    - assets/images/categoryDetailList/animals/ic_squirrel.png
    - assets/images/categoryDetailList/animals/ic_tiger.png
    - assets/images/categoryDetailList/animals/ic_wolf.png
    - assets/images/categoryDetailList/animals/ic_yak.png
    - assets/images/categoryDetailList/animals/ic_zebra.png
    - assets/images/categoryDetailList/birds/ic_bulbul.png
    - assets/images/categoryDetailList/birds/ic_crow.png
    - assets/images/categoryDetailList/birds/ic_cuckoo.png
    - assets/images/categoryDetailList/birds/ic_duck.png
    - assets/images/categoryDetailList/birds/ic_eagle.png
    - assets/images/categoryDetailList/birds/ic_emu.png
    - assets/images/categoryDetailList/birds/ic_flamingo.png
    - assets/images/categoryDetailList/birds/ic_goldfinch.png
    - assets/images/categoryDetailList/birds/ic_gulls.png
    - assets/images/categoryDetailList/birds/ic_hen.png
    - assets/images/categoryDetailList/birds/ic_heron.png
    - assets/images/categoryDetailList/birds/ic_hummingbird.png
    - assets/images/categoryDetailList/birds/ic_kingfisher.png
    - assets/images/categoryDetailList/birds/ic_myna.png
    - assets/images/categoryDetailList/birds/ic_parrot.png
    - assets/images/categoryDetailList/birds/ic_peacock.png
    - assets/images/categoryDetailList/birds/ic_penguin.png
    - assets/images/categoryDetailList/birds/ic_pigeon.png
    - assets/images/categoryDetailList/birds/ic_sparrow.png
    - assets/images/categoryDetailList/birds/ic_swan.png
    - assets/images/categoryDetailList/birds/ic_vulture.png
    - assets/images/categoryDetailList/birds/ic_woodpeacker.png
    - assets/images/categoryDetailList/birds/ic_yak.png
    - assets/images/categoryDetailList/birds/ic_owl.png
    - assets/images/categoryDetailList/vegetables/ic_beetroot.png
    - assets/images/categoryDetailList/vegetables/ic_bitergourd.png
    - assets/images/categoryDetailList/vegetables/ic_bottlegourd.png
    - assets/images/categoryDetailList/vegetables/ic_brinjal.png
    - assets/images/categoryDetailList/vegetables/ic_broccoli.png
    - assets/images/categoryDetailList/vegetables/ic_cabbage.png
    - assets/images/categoryDetailList/vegetables/ic_capsicum.png
    - assets/images/categoryDetailList/vegetables/ic_carrot.png
    - assets/images/categoryDetailList/vegetables/ic_cauliflower.png
    - assets/images/categoryDetailList/vegetables/ic_chilly.png
    - assets/images/categoryDetailList/vegetables/ic_clusterbeans.png
    - assets/images/categoryDetailList/vegetables/ic_corianderleaf.png
    - assets/images/categoryDetailList/vegetables/ic_corn.png
    - assets/images/categoryDetailList/vegetables/ic_cucumber.png
    - assets/images/categoryDetailList/vegetables/ic_curryleaf.png
    - assets/images/categoryDetailList/vegetables/ic_elephantfootyam.png
    - assets/images/categoryDetailList/vegetables/ic_fenugreek.png
    - assets/images/categoryDetailList/vegetables/ic_frenchbeans.png
    - assets/images/categoryDetailList/vegetables/ic_garlic.png
    - assets/images/categoryDetailList/vegetables/ic_gherkins.png
    - assets/images/categoryDetailList/vegetables/ic_ginger.png
    - assets/images/categoryDetailList/vegetables/ic_greenpeas.png
    - assets/images/categoryDetailList/vegetables/ic_ladyfinger.png
    - assets/images/categoryDetailList/vegetables/ic_limabeans.png
    - assets/images/categoryDetailList/vegetables/ic_mint.png
    - assets/images/categoryDetailList/vegetables/ic_mushroom.png
    - assets/images/categoryDetailList/vegetables/ic_onion.png
    - assets/images/categoryDetailList/vegetables/ic_potatoes.png
    - assets/images/categoryDetailList/vegetables/ic_raddish.png
    - assets/images/categoryDetailList/vegetables/ic_spinach.png
    - assets/images/categoryDetailList/vegetables/ic_squash.png
    - assets/images/categoryDetailList/vegetables/ic_sweetpotatoes.png
    - assets/images/categoryDetailList/vegetables/ic_tomato.png
    - assets/images/categoryDetailList/vegetables/ic_turnip.png
    - assets/images/drawing/ic_latter_draw_bg.png
    - assets/images/drawing/ic_sequre.png
    - assets/images/drawing/ic_circle.png
    - assets/images/drawing/ic_tringle.png
    - assets/images/drawing/ic_shape3.png
    - assets/images/drawing/ic_shape4.png
    - assets/images/drawing/ic_shape5.png
    - assets/images/drawing/ic_fill_image1.png
    - assets/images/drawing/ic_fill_image2.png
    - assets/images/drawing/ic_fill_image3.png
    - assets/images/drawing/ic_fill_image4.png
    - assets/images/drawing/ic_fill_image5.png
    - assets/images/drawing/ic_fill_image6.png
    - assets/images/drawing/ic_fill_image7.png
    - assets/images/drawing/ic_fill_image8.png
    - assets/images/drawing/ic_fill_image9.png
    - assets/images/drawing/ic_fill_image10.png
    - assets/images/drawing/ic_fill_image11.png
    - assets/images/drawing/ic_fill_image12.png
    - assets/images/drawing/ic_fill_image13.png
    - assets/images/drawing/ic_fill_image14.png
    - assets/images/drawing/ic_fill_image15.png
    - assets/images/drawing/ic_fill_image16.png
    - assets/images/drawing/ic_comingsoon.png
    - assets/images/TapSet/ic_shape1.png
    - assets/images/TapSet/ic_shape2.png
    - assets/images/TapSet/ic_shape3.png
    - assets/images/TapSet/ic_shape4.png
    - assets/images/TapSet/ic_shape5.png
    - assets/images/TapSet/ic_shape6.png
    - assets/images/TapSet/ic_shape7.png
    - assets/images/TapSet/ic_shape8.png
    - assets/images/TapSet/ic_shape9.png
    - assets/images/TapSet/ic_shape10.png
    - assets/images/TapSet/ic_tapset_bg.png
    - assets/images/TapSet/ic_circle.png
    - assets/images/TapSet/ic_main_box.png
    - assets/images/TapSet/ic_tapset_deatil_bg.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Black.ttf
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-Light.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
